name: CI-CD Manifest

on:
  pull_request:
    branches: [master, develop]
  push:
    branches: [master, develop]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      HUSKY: 0

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      - name: Install root dependencies
        run: npm install
      - name: Install dependencies (workspaces)
        run: npm ci --workspaces --ignore-scripts
      - name: Build App
        run: npm run build
      - name: Run tests
        run: npm run test:ci
